In [51]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [52]:
company = "Google"
company.lower()
# You can use this later to gather the data, by simply naming the files as the company name.

'google'

In [53]:
df = pd.read_csv(f"{company}.csv")

In [54]:
df = df.set_index(df[0:]['Year'])  #Removing the index 0,1,2,3 etc. So we can search easier later on.

In [56]:
df = pd.DataFrame(df)

In [57]:
df = df.replace('- -', np.nan)

In [58]:
df = df.drop(['Year'], axis=1)

In [59]:
df = df.drop(['FALSE', 'SEC Link'])

In [60]:
df = df.fillna(0)

df = df.replace('- -', np.nan)
df = df.replace('undefined', np.nan)
df = df.fillna(0)
df = df.drop(['FALSE', 'SEC Link'])
df

In [61]:
df = df.astype(float)/1000000

In [63]:
df = df.round(decimals=1)

In [72]:
df

,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Year,,,,,,,,,,,,,,,,,,,,,
Revenue,19.1,86.4,439.5,1465.9,3189.2,6138.6,10604.9,16594.0,21795.6,23650.6,...,50175.0,59825.0,66001.0,74989.0,90272.0,110855.0,136819.0,161857.0,182527.0,257637.0
COGS,6.1,14.2,131.5,625.9,1457.7,2571.5,4225.0,6649.1,8621.5,8844.1,...,20634.0,25858.0,25691.0,28164.0,35138.0,45583.0,59549.0,71896.0,84732.0,110939.0
Gross Profit,13.0,72.2,308.0,840.1,1731.6,3567.1,6379.9,9944.9,13174.0,14806.4,...,29541.0,33967.0,40310.0,46825.0,55134.0,65272.0,77270.0,89961.0,97795.0,146698.0
Gross Profit Ratio,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Research and Development Exp.,10.5,16.5,31.7,91.2,225.6,484.0,1228.6,2120.0,2793.2,2843.0,...,6793.0,7952.0,9832.0,12282.0,13948.0,16625.0,21419.0,26018.0,27573.0,31562.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Effect of Forex Changes on Cash,0.0,0.0,0.0,1.7,7.6,-21.8,19.7,40.0,-45.9,10.5,...,3.0,-3.0,-433.0,-434.0,-170.0,405.0,-302.0,-23.0,24.0,-287.0
Net Change In Cash,0.0,0.0,40.1,91.2,277.9,3450.3,-332.5,2536.9,2575.1,1540.9,...,4795.0,4120.0,-551.0,-1798.0,-3631.0,-2203.0,5986.0,1797.0,7967.0,-5520.0
Cash at the End of Period,0.0,0.0,57.8,149.0,426.9,3877.2,3544.7,6081.6,8656.7,10197.6,...,14778.0,18898.0,18347.0,16549.0,12918.0,10715.0,16701.0,18498.0,26465.0,20945.0
Cash at the Beginning of Period,0.0,0.0,17.7,57.8,149.0,426.9,3877.2,3544.7,6081.6,8656.7,...,9983.0,14778.0,18898.0,18347.0,16549.0,12918.0,10715.0,16701.0,18498.0,26465.0
Free Cash Flow,0.0,0.0,118.1,218.6,658.0,1621.2,1677.7,3372.6,5494.4,8506.3,...,13346.0,11301.0,11417.0,16109.0,25824.0,23907.0,22832.0,30972.0,42843.0,67012.0

In [ ]:
plt.plot(df.loc['Revenue'])

In [ ]:
df.loc['Revenue']

In [ ]:
goog = {
    {"Operating income": [df.loc['Operating Income']]},
    {"Net Receivables": [df.loc['Net Receivables']]},
    {"Inventory": [df.loc['Inventory']]},
    {"Other Current Assets": [df.loc['Other Current Assets']]},
    {"Accounts Payable": [df.loc['Accounts Payable']]},
    {"Deferred Revenue": [df.loc['Deferred Revenue']]},
    {"Other Current Liabilities": [df.loc['Other Current Liabilities']]},
    {"PP&E": [df.loc['PP&E']]},
    }

In [ ]:
gg1 = pd.DataFrame(data=goog)
gg1 = gg1.transpose()
gg1 = gg1.astype(float)/1000000
gg1

In [ ]:
gg1.loc['PP&E']

In [ ]:
nta = []
for i in range(len(gg1.loc['EBIT'])):
    nta.append(gg1.loc['Receivables'][i] + gg1.loc['Inventory'][i] + gg1.loc['OtherAssets'][i] + gg1.loc['PP&E'][i]
               - gg1.loc['AccountsPayable'][i] - gg1.loc['DeferredRevenue'][i] - gg1.loc['OtherLiabilities'][i])
    
nta = pd.Series(nta)

In [ ]:
ebit = gg1.loc['EBIT']
ppie = gg1.loc['PP&E']
x_ppie = [x for x in range(len(ppie))]
x_ebit = [x for x in range(len(ebit))]
x_nta = [x for x in range(len(nta))]

In [ ]:
ronta = []
for i in range(len(nta)):
    ronta.append(float((ebit[i]/nta[i])*100))
    
ronta = pd.Series(ronta)
ronta

In [ ]:
graph = plt.plot(ebit, label='Operating income')
graph = plt.plot(nta, label='Net Tangible Assets')
plt.xlabel('Years')
plt.ylabel("($ in millions)")
plt.title('Google')
plt.legend()

In [ ]:
fix, ax1 = plt.subplots()
ax1.bar(x_nta, nta, color = 'y', label = "Net tangible assets in millions")
plt.ylabel("Net tangible assets")
ax2 = ax1.twinx()
ax2.plot(ronta, color = 'g')
ax2.set_ylim([0, 200])
ax2.set_ylabel("% Return on net tangible assets")
plt.xlabel('Years')

plt.title(company)

#ax.plot(ebit, label = "Operating profit")